### ISSUE TITLE
False Positive Equality among Sums of Exponentials

### ISSUE THREAD

**Issue by sweeneyde** [Doenet/math-expressions#54]
Working on a student issue at https://github.com/mooculus/calculus/issues/178

Reproducer:

* git clone this repo
* npm install
* Add the following to the `var nonequivalences = ...` list in spec/slow_math-expressions.spec.js:
```diff
diff --git a/spec/slow_math-expressions.spec.js b/spec/slow_math-expressions.spec.js
index 380f669..cc751b8 100644
--- a/spec/slow_math-expressions.spec.js
+++ b/spec/slow_math-expressions.spec.js
@@ -449,6 +449,13 @@ describe("expression", function () {
     ['abs(x+10)-10', 'abs(x+11)-11'],
     ['abs(x+100)-100', 'abs(x+101)-101'],
     ['abs(x+1000)-1000', 'abs(x+1001)-1001'],
+    ['1/8 e^(2x) + 2e^(-2x)', '1/8 e^(2x) - 2e^(-2x)'],
+    ['1/8 e^(2x) + 2e^(-2x)', '1/8 e^(2x) + 1000e^(-3x)'],
+    ['1/8 e^(2x) + 2e^(-2x)', '1/8 e^(2x)'],
+    ['1/8 e^(2x) + 2e^(-2x)', '1/8 e^(2x) + .00001'],
+    ['1/64 e^(4x) - 1/2 + 4 e^(-4x)', '1/64 e^(4x) + 1/2 + 4 e^(-4x)'],
+    ['1/64 e^(4x) - 1/2 + 4 e^(-4x)', '1/64 e^(4x) - 1/2 + 4 e^(-4x) + 1000'],
+    ['1/64 e^(4x) - 1/2 + 4 e^(-4x)', '1/64 e^(4x) + 4 e^(-4x)'],
     // ['abs(x+1E5)-1E5', 'abs(x+1E5+1)-(1E5+1)'],
     // ['abs(x+1E10)-1E10', 'abs(x+1E10+1)-(1E10+1)'],
     ['x > 1000', 'x > 1001'],
```
* Run npm test slow_math-expressions
* Wait a minute and get 7 failed tests.

Full output:

<details>

```
PS C:\Users\sween\Desktop\math-expr-demo\math-expressions> npm test slow_math-expressions

> math-expressions@2.0.0-alpha63 test C:\Users\sween\Desktop\math-expr-demo\math-expressions
> jest quick_ "slow_math-expressions"

 PASS  spec/quick_latex-to-ast.spec.js (5.657 s)
 PASS  spec/quick_latex-to-ast-to-latex.spec.js (6.042 s)
 PASS  spec/quick_text-to-ast.spec.js
 PASS  spec/quick_text-to-ast-to-text.spec.js
 PASS  spec/quick_ast-to-latex.spec.js
 PASS  spec/quick_ast-to-text.spec.js
 PASS  spec/quick_ast-to-guppy.spec.js
 PASS  spec/quick_mml-to-latex.spec.js
 PASS  spec/quick_mathjs-to-ast.spec.js (9.233 s)
 PASS  spec/quick_ast-to-mathjs.spec.js (9.873 s)
 PASS  spec/quick_normalization.spec.js (10.834 s)
 PASS  spec/quick_trees.spec.js (11.393 s)
 PASS  spec/quick_arithmetic.spec.js (11.396 s)
 PASS  spec/quick_transformation.spec.js (12.052 s)
 PASS  spec/quick_solve.spec.js (13.511 s)
 PASS  spec/quick_rounding.spec.js (14.646 s)
 PASS  spec/quick_sets.spec.js (15.259 s)
 FAIL  spec/slow_math-expressions.spec.js (60.799 s)
  ● expression › 1/8 e^(2x) + 2e^(-2x) != 1/8 e^(2x) - 2e^(-2x)

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/8 e^(2x) + 2e^(-2x) != 1/8 e^(2x) + 1000e^(-3x)

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/8 e^(2x) + 2e^(-2x) != 1/8 e^(2x)

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/8 e^(2x) + 2e^(-2x) != 1/8 e^(2x) + .00001

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/64 e^(4x) - 1/2 + 4 e^(-4x) != 1/64 e^(4x) + 1/2 + 4 e^(-4x)

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/64 e^(4x) - 1/2 + 4 e^(-4x) != 1/64 e^(4x) - 1/2 + 4 e^(-4x) + 1000

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

  ● expression › 1/64 e^(4x) - 1/2 + 4 e^(-4x) != 1/64 e^(4x) + 4 e^(-4x)

    expect(received).toBeFalsy()

    Received: true

      515 |     it(lhs + " != " + rhs, function () {
      516 |       Expression.set_to_default();
    > 517 |       expect(Expression.fromText(lhs).equals(Expression.fromText(rhs))).toBeFalsy();
          |                                                                         ^
      518 |     });
      519 |   });
      520 |

      at Object.<anonymous> (spec/slow_math-expressions.spec.js:517:73)

Test Suites: 1 failed, 17 passed, 18 total
Tests:       7 failed, 1 skipped, 4059 passed, 4067 total
Snapshots:   0 total
Time:        72.705 s
Ran all test suites matching /quick_|slow_math-expressions/i.
npm ERR! Test failed.  See above for more details.
```
</details>

I believe these are valid tests cases to add, and that they currently fail, but let me know if I've misunderstood something.

**Comment by dqnykamp** [comment]
Unfortunately, these cases look to be examples of a known limitation of the numerical equality checker.  What always gets me is that "e^(-10x)" and "e^(-10x)+c" get falsely evaluated as equal, so the numerical equality checkers fails to detect if someone missed an integral constant.

The problem is that the numerical equality checker finds values (x,c) in C^2 where the difference between "e^(-10x)" and "e^(-10x)+c" smaller than the tolerance for all complex x and c in a neighborhood, i.e., where e^(-10x) is around a factor of 10^12 larger than c.

I'm not sure the best way to address this issue.  We can try tweaking the parameters of the algorithm to get specific cases to work properly.  For example, we could restrict the range of values checked so that it would take larger exponents to cause this failure (though that might make some other of the tests fail).  That would make both your examples and my example work, but then expressions involving e^(x^2) would presumably still fail.

**Comment by kisonecat** [comment]
I pushed 11110c16873b4656074fdf6b01328a8f70baade9 which includes a "finite field inequality checker."  This branch aims to implement https://dl.acm.org/doi/pdf/10.1145/800057.808698  The idea is to provide an interpretation for exponentials and trigonometric functions over finite fields, and when this is possible but yields different results, to then declare the two expressions as unequal.  This can distinguish between `1/8 e^(2x) + 2e^(-2x)` and `1/8 e^(2x) - 2e^(-2x)` and also between `e^(-10x)` and `e^(-10x)+c`.  Of course, I worry that it might distinguish between other things we DO want to adjudicate as being equal!

**Comment by dqnykamp** [comment]
All our tests pass, including the ones @sweeneyde described.  So if you think there are places where it will introduce additional failures, add those to the tests.

I changed maxden to default to 100000000 so it can distinguish 10^(-8).  I hope that doesn't make it too slow.

I extended the finite field inequality to vectors and relations and added more tests.  If no objections, I'll merge this in.

**Comment by kisonecat** [comment]
> I changed maxden to default to 100000000 so it can distinguish 10^(-8). I hope that doesn't make it too slow.

That shouldn't really affect the speed -- if we did the calculations over a large finite field, that would be slow.

I guess when this was first implemented, we were thinking of this as an *equality* test rather than an inequality test.  It's definitely a lot better as an inequality test.

> I extended the finite field inequality to vectors and relations and added more tests.

Amazing!  That is great!

**Comment by dqnykamp** [comment]
It seems that pi and log do not work for the finite field evaluation.  Is there a way to add support for them?

**Comment by dqnykamp** [comment]
@kisonecat, I also added some comments/questions for you on #55 that you might not get since I opened the PR.

**Comment by dqnykamp** [comment]
Added a commit to #55 to fix trig functions and apply to more general forms of expressions.  It is still broken for `x^0.5`, but will need @kisonecat to fix it.  It also doesn't work for `log(x)` or `pi`.

**Comment by dqnykamp** [comment]
It's not perfect, but I figured I'd merge it to at least get it working with exponentials and trig functions.
